import React from 'react';
import { 
  Award, 
  Sparkles, 
  TrendingUp, 
  CheckCircle2, 
  AlertCircle, 
  ShieldCheck, 
  DollarSign, 
  Zap,
  ArrowRight,
  Info,
  Layers,
  Clock,
  Star
} from 'lucide-react';
import { FinancialHealthScore, FinancialSummary, Statement } from '../types';

interface FinancialHealthViewProps {
  statement: Statement | null;
  healthScore: FinancialHealthScore | null;
  summary: FinancialSummary | null;
  isGeneratingSummary: boolean;
  onRegenerateSummary?: () => void;
}

export const FinancialHealthView: React.FC<FinancialHealthViewProps> = ({
  statement,
  healthScore,
  summary,
  isGeneratingSummary,
  onRegenerateSummary,
}) => {
  if (!healthScore) {
    return (
      <div className="p-12 text-center text-slate-400 space-y-3">
        <Sparkles className="w-8 h-8 text-indigo-500 mx-auto animate-spin" />
        <p>Computing composite financial health score and generating diagnostic summary...</p>
      </div>
    );
  }

  const score = healthScore.overall_score;
  const tierColor =
    score >= 80 ? 'text-emerald-600' : score >= 65 ? 'text-teal-600' : score >= 50 ? 'text-amber-600' : 'text-rose-600';
  const tierBg =
    score >= 80 ? 'bg-emerald-50 border-emerald-200' : score >= 65 ? 'bg-teal-50 border-teal-200' : score >= 50 ? 'bg-amber-50 border-amber-200' : 'bg-rose-50 border-rose-200';

  // SVG Circular Gauge calculation
  const radius = 70;
  const circumference = 2 * Math.PI * radius;
  const strokeDashoffset = circumference - (score / 100) * circumference;

  return (
    <div className="space-y-6 pb-12">
      
      {/* Top Banner: Composite Score Gauge & Executive Summary */}
      <div className="bg-white border border-slate-200/80 rounded-2xl p-6 sm:p-8 shadow-xs">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-center">
          
          {/* Circular Gauge Score (4 cols) */}
          <div className="lg:col-span-4 flex flex-col items-center justify-center p-6 bg-slate-50 border border-slate-200 rounded-2xl">
            <div className="relative w-44 h-44 flex items-center justify-center">
              <svg className="w-full h-full transform -rotate-90" viewBox="0 0 160 160">
                {/* Background Ring */}
                <circle
                  cx="80"
                  cy="80"
                  r={radius}
                  stroke="#e2e8f0"
                  strokeWidth="12"
                  fill="transparent"
                />
                {/* Score Progress Ring */}
                <circle
                  cx="80"
                  cy="80"
                  r={radius}
                  stroke={score >= 80 ? '#10b981' : score >= 65 ? '#14b8a6' : score >= 50 ? '#f59e0b' : '#f43f5e'}
                  strokeWidth="12"
                  strokeDasharray={circumference}
                  strokeDashoffset={strokeDashoffset}
                  strokeLinecap="round"
                  fill="transparent"
                  className="transition-all duration-1000 ease-out"
                />
              </svg>

              <div className="absolute inset-0 flex flex-col items-center justify-center text-center">
                <span className={`text-4xl sm:text-5xl font-black tracking-tight font-mono ${tierColor}`}>
                  {score}
                </span>
                <span className="text-[11px] font-semibold text-slate-400 uppercase tracking-widest mt-1">
                  Out of 100
                </span>
              </div>
            </div>

            <div className="mt-4 text-center space-y-1">
              <span className={`inline-block px-3 py-1 rounded-full text-xs font-extrabold uppercase tracking-wider border ${tierBg} ${tierColor}`}>
                {healthScore.tier} Tier
              </span>
              <p className="text-xs text-slate-500 max-w-xs">{healthScore.tier_description}</p>
            </div>
          </div>

          {/* AI Executive Summary & Core Metrics (8 cols) */}
          <div className="lg:col-span-8 space-y-5">
            <div className="flex items-center justify-between flex-wrap gap-2">
              <div className="flex items-center gap-2">
                <div className="p-1.5 bg-indigo-50 text-indigo-600 rounded-lg">
                  <Sparkles className="w-4 h-4" />
                </div>
                <div>
                  <h2 className="text-lg font-bold text-slate-900 tracking-tight">Financial Health Diagnostic Narrative</h2>
                  <p className="text-xs text-slate-500">Holistic financial diagnosis generated by Gemini 3.7 Flash</p>
                </div>
              </div>

              {onRegenerateSummary && (
                <button
                  onClick={onRegenerateSummary}
                  disabled={isGeneratingSummary}
                  className="px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-colors"
                >
                  <Sparkles className="w-3.5 h-3.5 text-indigo-600" />
                  <span>{isGeneratingSummary ? 'Refreshing...' : 'Regenerate Narrative'}</span>
                </button>
              )}
            </div>

            {/* Paragraphs */}
            <div className="bg-slate-50 border border-slate-200 p-5 rounded-2xl space-y-3 text-xs sm:text-sm text-slate-700 leading-relaxed">
              <p className="font-semibold text-indigo-900 text-sm">
                {summary?.executive_summary || 'Analysis complete: cashflow profile exhibits positive operational retention.'}
              </p>
              {summary?.detailed_paragraphs?.map((para, i) => (
                <p key={i} className="text-slate-600">{para}</p>
              ))}
            </div>

            {/* Key Vital Metric Badges */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 font-mono text-xs">
              <div className="p-3 bg-slate-50 border border-slate-200 rounded-xl">
                <span className="text-slate-400 block text-[10px]">SAVINGS RETENTION</span>
                <span className="text-emerald-600 font-bold text-sm">{healthScore.metrics.savings_rate_percent}%</span>
              </div>
              <div className="p-3 bg-slate-50 border border-slate-200 rounded-xl">
                <span className="text-slate-400 block text-[10px]">FIXED BURDEN</span>
                <span className="text-blue-600 font-bold text-sm">₹{healthScore.metrics.fixed_recurring_monthly.toLocaleString()}/mo</span>
              </div>
              <div className="p-3 bg-slate-50 border border-slate-200 rounded-xl">
                <span className="text-slate-400 block text-[10px]">DISCRETIONARY RATIO</span>
                <span className="text-purple-600 font-bold text-sm">{healthScore.metrics.discretionary_spend_percent}%</span>
              </div>
              <div className="p-3 bg-slate-50 border border-slate-200 rounded-xl">
                <span className="text-slate-400 block text-[10px]">EST. RUNWAY</span>
                <span className="text-amber-600 font-bold text-sm">{healthScore.metrics.runway_days_estimate} Days</span>
              </div>
            </div>

          </div>

        </div>
      </div>

      {/* Factor Breakdown (How it's calculated) */}
      <div className="bg-white border border-slate-200/80 p-6 sm:p-8 rounded-2xl shadow-xs space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 pb-4 border-b border-slate-100">
          <div>
            <h3 className="text-lg font-bold text-slate-900 tracking-tight">Mathematical Factor Breakdown &amp; Scoring Formulas</h3>
            <p className="text-xs text-slate-500">Transparent mathematical attribution across the 4 pillars of financial resilience</p>
          </div>
          <span className="text-xs font-mono text-emerald-700 bg-emerald-50 px-2.5 py-1 rounded-lg border border-emerald-200 self-start sm:self-auto font-bold">
            100% Deterministic &amp; Auditable
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {healthScore.factors.map((factor) => {
            const isHigh = factor.score >= 80;
            const isMed = factor.score >= 60;
            const factorColor = isHigh ? 'text-emerald-600' : isMed ? 'text-amber-600' : 'text-rose-600';
            const progressBg = isHigh ? 'bg-emerald-500' : isMed ? 'bg-amber-500' : 'bg-rose-500';

            return (
              <div key={factor.key} className="p-5 bg-slate-50 border border-slate-200 rounded-2xl space-y-3">
                <div className="flex items-center justify-between">
                  <div>
                    <h4 className="text-sm font-bold text-slate-900">{factor.name}</h4>
                    <span className="text-[11px] text-slate-500 font-mono">Weight: {(factor.weight * 100).toFixed(0)}% of Composite Score</span>
                  </div>
                  <div className="text-right">
                    <span className={`text-xl font-extrabold font-mono ${factorColor}`}>{factor.score}</span>
                    <span className="text-xs text-slate-400">/100</span>
                  </div>
                </div>

                {/* Progress bar */}
                <div className="w-full bg-slate-200 h-2 rounded-full overflow-hidden">
                  <div className={`h-full rounded-full ${progressBg}`} style={{ width: `${factor.score}%` }} />
                </div>

                {/* Actual value vs Benchmark */}
                <div className="grid grid-cols-2 gap-2 text-[11px] pt-1 border-t border-slate-200 font-mono">
                  <div>
                    <span className="text-slate-400 block">ACTUAL MEASURED</span>
                    <span className="text-slate-900 font-bold">{factor.actual_value}</span>
                  </div>
                  <div>
                    <span className="text-slate-400 block">HEALTHY BENCHMARK</span>
                    <span className="text-emerald-600 font-bold">{factor.benchmark}</span>
                  </div>
                </div>

                {/* Formula note */}
                <div className="p-2 bg-white rounded-lg border border-slate-200/80 text-[11px] text-slate-600 flex items-start gap-1.5">
                  <Info className="w-3.5 h-3.5 text-slate-400 shrink-0 mt-0.5" />
                  <span><strong>Calculation Formula:</strong> <code className="text-slate-800 font-mono">{factor.formula}</code></span>
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Actionable Suggestions */}
      <div className="bg-white border border-slate-200/80 p-6 sm:p-8 rounded-2xl shadow-xs space-y-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="p-1.5 bg-emerald-50 text-emerald-600 rounded-lg">
              <Zap className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900 tracking-tight">Concrete Actionable Savings Opportunities</h3>
              <p className="text-xs text-slate-500">High-impact financial optimizations with estimated rupee savings</p>
            </div>
          </div>
          <span className="text-xs font-mono text-emerald-700 bg-emerald-50 px-3 py-1 rounded-full border border-emerald-200 font-bold">
            Potential Savings: ~₹{summary?.actionable_suggestions.reduce((s, a) => s + a.potential_monthly_savings, 0).toLocaleString()}/mo
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {summary?.actionable_suggestions.map((sug, idx) => (
            <div
              key={idx}
              className="p-5 bg-slate-50 border border-slate-200 rounded-2xl space-y-3 flex flex-col justify-between"
            >
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="px-2 py-0.5 bg-indigo-50 text-indigo-700 rounded text-[10px] font-bold">
                    {sug.category}
                  </span>
                  <span className="px-2 py-0.5 bg-slate-200 text-slate-700 rounded text-[10px] font-semibold">
                    {sug.impact} Impact
                  </span>
                </div>
                <h4 className="text-sm font-bold text-slate-900">{sug.title}</h4>
                <p className="text-xs text-slate-600 leading-relaxed">{sug.description}</p>
              </div>

              <div className="pt-3 border-t border-slate-200 flex items-center justify-between text-xs font-mono">
                <span className="text-slate-500">EST. SAVINGS</span>
                <span className="text-emerald-600 font-extrabold text-sm">+₹{sug.potential_monthly_savings.toLocaleString()}/mo</span>
              </div>
            </div>
          ))}
        </div>
      </div>

    </div>
  );
};
